# Generated by Django 4.2 on 2023-04-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0002_menu_slug_alter_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='named_url_kwargs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Named URL kwargs'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tree_menu.menu', verbose_name='menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Named URL'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
    ]
